#!/bin/bash

timestamp=$(date +'%T-%d-%m-%Y')

cd "$MYNOTES/noteVault"

if [[ `git status --porcelain` ]]; then
  git pull origin main
  git add .
  git commit -m "auto-backup: $timestamp"
  git push origin main
fi


